version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: broker
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: chat_password
      POSTGRES_DB: chat_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

#  auth:
#    build:
#      context: .
#      dockerfile: docker/auth.Dockerfile
#    container_name: auth_service
#    depends_on:
#      - postgres
#    ports:
#      - "8081:8081"
#    environment:
#      DB_HOST: postgres
#      DB_USER: chat_user
#      DB_PASS: chat_password
#      DB_NAME: chat_db

#  chat:
#    build:
#      context: .
#      dockerfile: docker/chat.Dockerfile
#    container_name: chat_service
#    depends_on:
#      - rabbitmq
#    ports:
#      - "8082:8082"
#    environment:
#      RABBITMQ_URL: amqp://user:password@broker:5672/
#
#  bot:
#    build:
#      context: .
#      dockerfile: docker/bot.Dockerfile
#    container_name: bot_service
#    depends_on:
#      - rabbitmq
#    environment:
#      RABBITMQ_URL: amqp://user:password@broker:5672/
