// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	domain "github.com/ivofreitas/chat/internal/auth/domain"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mocks type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateUser provides a mocks function with given fields: email, hashedPassword
func (_m *Repository) CreateUser(email string, hashedPassword string) error {
	ret := _m.Called(email, hashedPassword)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(email, hashedPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserByEmail provides a mocks function with given fields: email
func (_m *Repository) GetUserByEmail(email string) (*domain.User, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.User, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.User); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mocks and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
